encoded sequences are saved in RNA_tr#0.5k_num1_seq25580_codefw.npy
encoded sequences are saved in DNA_tr#0.5k_num1_seq30067_codefw.npy
encoded sequences are saved in RNA_val#0.5k_num1_seq2359_codefw.npy
encoded sequences are saved in DNA_val#0.5k_num1_seq77_codefw.npy
encoded sequences are saved in RNA_tr#1k_num1_seq12390_codefw.npy
encoded sequences are saved in DNA_tr#1k_num1_seq15013_codefw.npy
encoded sequences are saved in RNA_val#1k_num1_seq1122_codefw.npy
encoded sequences are saved in DNA_val#1k_num1_seq35_codefw.npy
encoded sequences are saved in RNA_tr#2k_num1_seq5760_codefw.npy
encoded sequences are saved in DNA_tr#2k_num1_seq7485_codefw.npy
encoded sequences are saved in RNA_val#2k_num1_seq516_codefw.npy
encoded sequences are saved in DNA_val#2k_num1_seq15_codefw.npy
...loading data...
...loading RNA virus data...
data for training RNA_tr#0.5k_num1_seq25580_codefw.npy
data for validation RNA_val#0.5k_num1_seq2359_codefw.npy
...loading DNA virus data...
data for training DNA_tr#0.5k_num1_seq30067_codefw.npy
data for validation DNA_val#0.5k_num1_seq77_codefw.npy
...combining all training data...
...shuffling training data...
...building model...
...fitting model...
0.5k_fl10_fn500_dn500_ep10
Train on 55647 samples, validate on 2436 samples
Epoch 1/10
 - 547s - loss: 0.3346 - accuracy: 0.8493 - val_loss: 0.2045 - val_accuracy: 0.9347

Epoch 00001: val_loss improved from inf to 0.20455, saving model to ./training_data/models/model_siamese_varlen_0.5k_fl10_fn500_dn500.h5
Epoch 2/10
 - 554s - loss: 0.2575 - accuracy: 0.8907 - val_loss: 0.2451 - val_accuracy: 0.9048

Epoch 00002: val_loss did not improve from 0.20455
Epoch 3/10
 - 556s - loss: 0.2357 - accuracy: 0.9017 - val_loss: 0.2410 - val_accuracy: 0.9085

Epoch 00003: val_loss did not improve from 0.20455
Epoch 4/10
 - 556s - loss: 0.2248 - accuracy: 0.9063 - val_loss: 0.4035 - val_accuracy: 0.8264

Epoch 00004: val_loss did not improve from 0.20455
Epoch 5/10
 - 557s - loss: 0.2099 - accuracy: 0.9126 - val_loss: 0.2426 - val_accuracy: 0.9076

Epoch 00005: val_loss did not improve from 0.20455
Epoch 6/10
 - 560s - loss: 0.2001 - accuracy: 0.9165 - val_loss: 0.3752 - val_accuracy: 0.8461

Epoch 00006: val_loss did not improve from 0.20455
Epoch 7/10
 - 559s - loss: 0.1901 - accuracy: 0.9220 - val_loss: 0.2775 - val_accuracy: 0.8883

Epoch 00007: val_loss did not improve from 0.20455
Epoch 8/10
 - 558s - loss: 0.1821 - accuracy: 0.9242 - val_loss: 0.6227 - val_accuracy: 0.7615

Epoch 00008: val_loss did not improve from 0.20455
Epoch 9/10
 - 558s - loss: 0.1747 - accuracy: 0.9273 - val_loss: 0.5155 - val_accuracy: 0.8108

Epoch 00009: val_loss did not improve from 0.20455
Epoch 10/10
 - 559s - loss: 0.1643 - accuracy: 0.9315 - val_loss: 0.4450 - val_accuracy: 0.8350
Using Theano backend.
/opt/ohpc/pub/anaconda3/lib/python3.7/site-packages/keras/callbacks/callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_acc` which is not available. Available metrics are: val_loss,val_accuracy,loss,accuracy
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning

Epoch 00010: val_loss did not improve from 0.20455
...predicting tr...

auc_tr=0.991546605986271

...predicting val...

auc_val=0.9525552870190428

...loading data...
...loading RNA virus data...
data for training RNA_tr#1k_num1_seq12390_codefw.npy
data for validation RNA_val#1k_num1_seq1122_codefw.npy
...loading DNA virus data...
data for training DNA_tr#1k_num1_seq15013_codefw.npy
data for validation DNA_val#1k_num1_seq35_codefw.npy
...combining all training data...
...shuffling training data...
...building model...
...fitting model...
1k_fl10_fn500_dn500_ep10
Train on 27403 samples, validate on 1157 samples
Epoch 1/10
 - 605s - loss: 0.3317 - accuracy: 0.8467 - val_loss: 0.3100 - val_accuracy: 0.8660

Epoch 00001: val_loss improved from inf to 0.31001, saving model to ./training_data/models/model_siamese_varlen_1k_fl10_fn500_dn500.h5
Epoch 2/10
 - 607s - loss: 0.1937 - accuracy: 0.9197 - val_loss: 0.0927 - val_accuracy: 0.9689

Epoch 00002: val_loss improved from 0.31001 to 0.09269, saving model to ./training_data/models/model_siamese_varlen_1k_fl10_fn500_dn500.h5
Epoch 3/10
 - 608s - loss: 0.1639 - accuracy: 0.9335 - val_loss: 0.2522 - val_accuracy: 0.8911

Epoch 00003: val_loss did not improve from 0.09269
Epoch 4/10
 - 608s - loss: 0.1444 - accuracy: 0.9430 - val_loss: 0.2545 - val_accuracy: 0.8911

Epoch 00004: val_loss did not improve from 0.09269
Epoch 5/10
 - 659s - loss: 0.1334 - accuracy: 0.9468 - val_loss: 0.2988 - val_accuracy: 0.8773

Epoch 00005: val_loss did not improve from 0.09269
Epoch 6/10
 - 1045s - loss: 0.1169 - accuracy: 0.9526 - val_loss: 0.4271 - val_accuracy: 0.8427

Epoch 00006: val_loss did not improve from 0.09269
Epoch 7/10
 - 610s - loss: 0.1116 - accuracy: 0.9562 - val_loss: 0.1776 - val_accuracy: 0.9369

Epoch 00007: val_loss did not improve from 0.09269
Epoch 8/10
 - 611s - loss: 0.1045 - accuracy: 0.9574 - val_loss: 0.1759 - val_accuracy: 0.9300

Epoch 00008: val_loss did not improve from 0.09269
Epoch 9/10
 - 611s - loss: 0.1008 - accuracy: 0.9603 - val_loss: 0.0720 - val_accuracy: 0.9715

Epoch 00009: val_loss improved from 0.09269 to 0.07204, saving model to ./training_data/models/model_siamese_varlen_1k_fl10_fn500_dn500.h5
Epoch 10/10
 - 611s - loss: 0.0926 - accuracy: 0.9627 - val_loss: 0.2231 - val_accuracy: 0.9127
Using Theano backend.
/opt/ohpc/pub/anaconda3/lib/python3.7/site-packages/keras/callbacks/callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_acc` which is not available. Available metrics are: val_loss,val_accuracy,loss,accuracy
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning

Epoch 00010: val_loss did not improve from 0.07204
...predicting tr...

auc_tr=0.9991004836432584

...predicting val...

auc_val=0.9787624140565316

...loading data...
...loading RNA virus data...
data for training RNA_tr#2k_num1_seq5760_codefw.npy
data for validation RNA_val#2k_num1_seq516_codefw.npy
...loading DNA virus data...
data for training DNA_tr#2k_num1_seq7485_codefw.npy
data for validation DNA_val#2k_num1_seq15_codefw.npy
...combining all training data...
...shuffling training data...
...building model...
...fitting model...
2k_fl10_fn500_dn500_ep10
Train on 13245 samples, validate on 531 samples
Epoch 1/10
 - 585s - loss: 0.3780 - accuracy: 0.8228 - val_loss: 0.3338 - val_accuracy: 0.8512

Epoch 00001: val_loss improved from inf to 0.33382, saving model to ./training_data/models/model_siamese_varlen_2k_fl10_fn500_dn500.h5
Epoch 2/10
 - 588s - loss: 0.1717 - accuracy: 0.9344 - val_loss: 0.3341 - val_accuracy: 0.8512

Epoch 00002: val_loss did not improve from 0.33382
Epoch 3/10
 - 589s - loss: 0.1177 - accuracy: 0.9561 - val_loss: 0.1974 - val_accuracy: 0.9115

Epoch 00003: val_loss improved from 0.33382 to 0.19736, saving model to ./training_data/models/model_siamese_varlen_2k_fl10_fn500_dn500.h5
Epoch 4/10
 - 589s - loss: 0.0974 - accuracy: 0.9638 - val_loss: 0.4165 - val_accuracy: 0.8380

Epoch 00004: val_loss did not improve from 0.19736
Epoch 5/10
 - 589s - loss: 0.0744 - accuracy: 0.9735 - val_loss: 0.3561 - val_accuracy: 0.8832

Epoch 00005: val_loss did not improve from 0.19736
Epoch 6/10
 - 590s - loss: 0.0690 - accuracy: 0.9717 - val_loss: 0.2692 - val_accuracy: 0.9153

Epoch 00006: val_loss did not improve from 0.19736
Epoch 7/10
 - 590s - loss: 0.0605 - accuracy: 0.9787 - val_loss: 0.1458 - val_accuracy: 0.9454

Epoch 00007: val_loss improved from 0.19736 to 0.14577, saving model to ./training_data/models/model_siamese_varlen_2k_fl10_fn500_dn500.h5
Epoch 8/10
 - 590s - loss: 0.0636 - accuracy: 0.9762 - val_loss: 0.5921 - val_accuracy: 0.8023

Epoch 00008: val_loss did not improve from 0.14577
Epoch 9/10
 - 590s - loss: 0.0492 - accuracy: 0.9842 - val_loss: 0.0431 - val_accuracy: 0.9868

Epoch 00009: val_loss improved from 0.14577 to 0.04305, saving model to ./training_data/models/model_siamese_varlen_2k_fl10_fn500_dn500.h5
Epoch 10/10
 - 621s - loss: 0.0550 - accuracy: 0.9797 - val_loss: 0.2213 - val_accuracy: 0.9247
Using Theano backend.
/opt/ohpc/pub/anaconda3/lib/python3.7/site-packages/keras/callbacks/callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_acc` which is not available. Available metrics are: val_loss,val_accuracy,loss,accuracy
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning

Epoch 00010: val_loss did not improve from 0.04305
...predicting tr...

auc_tr=0.9999398565649817

...predicting val...

auc_val=0.9919896640826873

